### ISSUE TITLE
Roles access is not controlled

### ISSUE THREAD

**Issue by th0mas** [dwyl/auth#116]
Access to roles is not currently authorised allowing for:

+ Anyone to view all roles for all apps.
+ Anyone to create/read/update/delete arbitrary roles.
+ Create roles under arbitrary apps using simple parameter injection.

This should probably be restricted in future

**Comment by nelsonic** [comment]
At present we are not _restricting_ access to roles because it's difficult to perform a permanently destructive action on them. Our "**delete**" button is a "soft delete" so `admin` can easily recover any data. 
But I 100% agree that we want to:
+ [ ] make role names globally unique so that people cannot create arbitrary "superadmin" roles.
  > this is especially relevant if RBAC.has_role?/2 checks for a `String` e.g.: `RBAC.has_role?(role_list, "superadmin")`
+ [ ] restrict CRUD for roles to apps the person owns
+ [ ] always lookup ownership on every action.

**Comment by nelsonic** [comment]
Role created in Firefox while logged in with GitHub:
![image](https://user-images.githubusercontent.com/194400/93382761-80cec100-f85a-11ea-89f8-c7735fa94fc6.png)

Not viewable when logged in with a different account in Safari:
![image](https://user-images.githubusercontent.com/194400/93382781-8af0bf80-f85a-11ea-9aec-4cc430d77744.png)

Happy to rework error pages to be more friendly later. 
Right now just focussing on limiting access.

**Comment by nelsonic** [comment]
Hi @th0mas, 👋  
I have made a first pass at restricting CRUD for roles:
https://github.com/dwyl/auth/blob/23df8070f7a39e09a70420dbb0ea3f3eb3bcdad9/lib/auth_web/controllers/role_controller.ex

I've written tests for all the restrictions and I think code is (_mostly_) readable.
It can _definitely_ be improved/refactored (_later_), right now we just want to confirm that the restrictions _work_ so that we can _use_ the feature without fear of someone accidentally (_or maliciously_) deleting/modifying a `role` that we are relying on. 💭 

LMK what you think. 👍  (_thanks!_)

**Comment by th0mas** [comment]
Yeah this looks a lot better and dramatically reduces the attack surface area of `auth`.

Happy to close this now 🎉
