### ISSUE TITLE
How to resolve the circular dependency with `auth_plug`?

### ISSUE THREAD

**Issue by tadasajon** [dwyl/auth#170]
First, let me make it clear that what I am trying to do is deploy this `auth` app at my own domain: https://authix.org.

This code base depends on `auth_plug`, as can be determined from `mix.exs`:
```
{:auth_plug, "~> 1.4.7"},
```

But the instructions for `auth_plug` are clear that in order for it to work you have to first get an `AUTH_API_KEY`: https://github.com/dwyl/auth_plug#2-get-your-auth_api_key-

But, the instructions for getting the `AUTH_API_KEY` tell me to go to URL where the `auth` app is deployed and get an `AUTH_API_KEY`.

But that is circular because what I am trying to do is to deploy this `auth` app to a domain in the first place.  How can I get the `AUTH_API_KEY` if I can't deploy the app that gives me the `AUTH_API_KEY`?

Should I just make up an `AUTH_API_KEY`?  Should I just get an `AUTH_API_KEY` from https://dwylauth.herokuapp.com even though I don't want anything to do with that domain and am trying to deploy the `auth` app to https://authix.org?

Is it the intention of the authors of this `auth` app that it should be possible for someone to deploy it to a domain of their own choosing?

**Comment by nelsonic** [comment]
Once PR #175 is merged `auth` app will _start_ without having an `AUTH_API_KEY` environment variable defined.
(_i.e. the dependency on `auth_plug` will not **block** the start-up of `auth`_)
And running `iex -S mix` follow by `Auth.Init.main()` will create all the necessary records to get started.
That will produce an `AUTH_API_KEY` which can be exported and then everything should work.

**Comment by nelsonic** [comment]
I think this resolved now. 
When you deploy an instance of the `auth` App to a new hosting provider 
and visit `auth.yourdomain.com/init` you will see the init page, e.g: https://authdev.herokuapp.com/init

The `/init` page will inform you if the `AUTH_API_KEY` environment variable is defined.

**`if`** the `AUTH_API_KEY` environment variable is **_not_ defined**, 
**`then`** it will be output in the logs for the admin to export.
**`when`** the `AUTH_API_KEY` environment variable has been exported (_or otherwise made available_),
***`and`*** the  `auth` App is restarted so that it can pickup the variable.
**`then`** everything will work as expected and you can start using the `auth` App.

Hope this adequately addresses the OP. 🤞 
@tadasajon please re-open and comment if not. 💬 
Thanks! 🙌
