### ISSUE TITLE
How to use in other projects?

### ISSUE THREAD

**Issue by Danwhy** [dwyl/auth#25]
@nelsonic
What we've got so far is a working implementation of auth in an example app, but how should we go about using it in other projects? 

Is the intention to keep the code in the form it is now when requiring it into other apps? By this I mean the logic being performed in the `controllers` so that all the parent application has to do is forward all requests to `/auth` endpoints to this application, rather than the alternative which, would just be exposing the functions in this app and the parent module calling these functions to perform authorisation.

You mentioned in https://github.com/dwyl/technology-stack/issues/67#issuecomment-437145610 that Auth should eventually be its own, separately hosted umbrella app, so to me this does seem like a step towards that.

I have managed to get this method of integrating the apps working, but just wanted to check I wasn't heading in the wrong direction. 

The main issue I had in getting this approach to work was the configuration. Dependency config files are not included when they are required as a dependency, as it is expected that the calling module will provide the config. 
This was a problem as the Ueberauth plug that is being used in the `auth_controller` expects some configuration to be set before it is compiled, so an error was being thrown. My solution to overcome this was to use `Application.put_env` to set the config before the plug is called. This way we can set the config we want to specify in `Auth`, and also read from the parent app's config file (with `Application.get_env`), allowing certain configurations to be set.

**Comment by nelsonic** [comment]
@Danwhy firstly _thank you_ for _proactively_ opening this issue 
to ask this question and capture the resulting research, discussion and answer. 🥇 

As described in the diagram and accompanying text in https://github.com/dwyl/technology-stack/issues/67 `auth` 
needs to be a "general purpose" authentication solution that we can "drop-in" to any App. 
I expect it to take us _decent_ chunk of effort to get it to the point where I will feel "happy".

Yes, the plan is to namespace all controllers under `/auth` such that any app that _uses_ the `auth` package forwards requests to the `/auth` endpoints. 
I do not foresee a situation where the "main" application would _invoke_ an `auth` function. 💭 
Instead, I expect us to have an `auth_config.exs` file (_name TBD_) where all options 
are clearly listed declaratively in order to override our (_carefully considered_) `default` values. 

If you are heading in the **Umbrella App** direction, then you are on the "***right track***". ✅ 
(_at least to my knowledge of Phoenix, this is still the way it's done in Programming Phoenix 1.4 [book]_)

We need a _separate_ issue for how we are going to require the `auth_config.exs` file.
(_as always, feel free to take the lead on opening it and assign if you have questions..._)

> _**To be clear** we aren't going to use [**`Überauth`**](https://github.com/ueberauth/ueberauth) because my recent reading of the source code indicated that it only provides a **superficial** functionality and then requires us (the "**integrators**") to provide the rest. [**`Guardian`**](https://github.com/ueberauth/guardian) is a closer approximation of what we need but it's still **miles off** the end result.  We can use these two packages as "**inspiration**" and even ["**borrow**"](https://youtu.be/CW0DUg63lqU) chunks of code (with the appropriate attribution), but we are _not_ going to use either as a _dependency_ because they are **not** "fit for purpose"; not even close.
So _please_ ignore any code that uses **`Überauth`** as it will be ***`DELETED`*** in due course_. 
![banksy-steal](https://user-images.githubusercontent.com/194400/51081671-2ed0b200-16ed-11e9-9ae9-b1f5c916e44e.jpg)


I am **_very_ grateful** that you made the effort to update the PR: https://github.com/dwyl/auth/pull/9 to Phoenix 1.4 
but we need to "take a step back" and focus on the dependencies of **`auth`** as described in [#67](https://github.com/dwyl/technology-stack/issues/67)

Specifically the "foundational" module [**`alog`**](https://github.com/dwyl/alog) is only about **10% complete** 
and it needs to be at around **80%** ***`before`*** we can _begin_ work on **`auth`**. 
The current [**`master`**](https://github.com/dwyl/alog/tree/2806915905a6bb0010a87f6587815c75a69ff02a) is only 5% documented which has lead members 
of @dwyl's core team to be "confused" as to how it works ... 
we _cannot_ afford for the documentation of any of our code to be less than "_wow_". 

> _**To be clear**: this is not a "criticism" of your work, Dan, you have done a "**good job**" so far on getting **`alog`** to "Alpha" state so that it could be **used** in the client project. **Thank you**_! 👍 
> _Just that we need to **keep going** on building the **foundation `before`** we build the **fortress**_. 🏰 

@SimonLab has made a _start_ with documenting **`alog`**: https://github.com/dwyl/alog/pull/20
(_and that PR **must** be finished **ASAP**_)

But we will need to _re-work_ some of the "internals" of **`alog`** to use a [**`cid`**](https://github.com/dwyl/cid) ("_Content ID_") _instead_ of an **`entry_id`** so that our records are identified by the hash of the content rather than by a **_random_ `UUID`**. 
I opened the issue to _discuss_ this: https://github.com/dwyl/alog/issues/15 but I did not _impose_ my preference at the time because I did not want to **distract** you or the team working on the client project as it would have **delayed** the shipping of the client project to work on [**`cid`**](https://github.com/dwyl/cid). 
Now that the client project has _shipped_ (🎉) and we have a little time to _breath_, ☁️ 
we need to put in the time to _re-work_ how **`alog`** operates to ensure 
that we create the appropriate foundation for our apps.

With that in mind, I need _your_ help with the following issue: https://github.com/dwyl/cid/issues/11
We need to implement a **`cid`** function that produces a consistent/deterministic hash of any content so that when we append a record to our append-only-log, we can _easily_ see when data changes (_or when the record was submitted with identical data and thus no DB insertion is required_).

Once the **`cid`** is working, we can use it in **`alog`** which in turn will be used by **`auth`**.
All login attempts and success need to be logged in an append-only (_auditable_) log.
Therefore we _must_ get the underlying layer _right_ ***`before`*** we proceed.
Sessions will be stored in **`alog`** and all **metrics** / **events** will be **`alog`** such as "verification email sent", "account verified", "password reset email sent", etc.

> Your benchmark as a "_senior_" developer _must_ be that:
_members of the **wider community**_ (_beyond @dwyl team_) _are using the code you write_.
If you achieve **code re-use** beyond your _own_ immediate needs, you have **levelled up** to "senior". 
Right now **`alog`** is not in a "_useable_" state for anyone beyond "us" (@dwyl).
The functionality and docs need to get to the point where people in the wider Elixir community 
_can_ use them. When we see the _first_ issue being opened by someone who is not _already_ a member of @dwyl then we _know_ that we have achieved reuse-ability / usefulness. 

Please continue to open/ask questions like this one.

# _Answer_

Re-read the Programming Phoenix 1.4 Book and see how Auth is done in the book. 
Then _apply_ that knowledge to an append-only log using **`alog`** (_with **`cid`** as ids_).
The resulting **`auth`** package should be an Umbrella App that _any_ other Phoenix App can use.

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/auth/issues/42
