### ISSUE TITLE
When to apply versioning 

### ISSUE THREAD

**Issue by RobStallion** [dwyl/auth#29]
@nelsonic We recently spoke about the types of tables that will be needed to create the auth module. 

Almost all of the tables had a primary key of a CID.

I understand using a CID in some of the tables (for example, a users table). There was a table, `roles` which was suggested, that didn't seem to have any confidential information in it but still contained a cid rather than a regular auto incrementing id. 

I was wondering when is it 'over complication' to use a CID?

**Comment by nelsonic** [comment]
@RobStallion _great_ question and _thank you_ for opening it so we can capture the discussion! 👍 

This question comes down to the following: how much _effort_ would we/you incur to make it _easy_ for end-users of our apps to "undo" _any_ change they made and thus have _complete confidence_ in our App?

# UX vs. Dev Time (Tradeoff)

Most software development decisions come down to this decision. 
How much developer effort to put into a feature in order to hit the "sweet spot" of UX?

We want to allow people to "roll back" _any_ change in _any_ "table" at _any_ time. 
We want the integrity of each row to be "cryptographically provable" to avoid any doubt.
This might sound like "overkill" for some tables ... but it won't be when we _need_ to know who _changed_ a role, who _updated_ the permissions or who _granted_ a role to a given user.

> A malicious user could simply create a role called "basic user" and grant it "admin_all" permissions.
Then grant this role to a "dormant" user which they never use until after they leave the company ...
I _know_ this sounds "_convoluted_" but it's how "inside job" hacks are perpetrated. Which is why database audits are so important in financial services companies. Is this going to happen in CS? or in the @dwyl App? (_I hope not_) but I'd much rather _proactively_ defend against it and then anyone _else_ using our Auth system knows it's there and they can use it too. 


To _answer_ your question regarding having **`CID`** as PK in the **`roles`** table:
I _agree_ that there won't be many changes to **`roles`** and we _could_ make the PK an **`int`** for _simplicity_.
But when you think how much disk space it will take to use a CID (_which we will "truncate" for a "non-distributed" of Auth_) is _negligible_ in the scheme of things. 



The way you could (_should?_) think about versioning is to ask the following ("proxy") question:

## How likely is it that this data will be _accidentally_ changed?

i.e. will this data get changed and require a **`ctrl+z`** to restore it to the previous version?

A further ("proxy") question is: 

## How do we ensure _accountability_ for changes in data?

If it's _possible_ that someone else would change an item of data? 
_e.g. because an account was **defaced** by friend as a "joke" or an ex-partner as "revenge", 
don't laugh, this is almost **inevitable** in a moderately successful system!_ 😞 

# Why _Not_ use an `int` Primary Key?

In our superficially simple use case, I _agree_, that _initially_ using an (auto-increment/serial) **`int`** as primary key will be _familiar_ to people who have used PostgreSQL before. However, anyone who has had exposure to more systems (_e.g: [Salesforce](https://help.salesforce.com/articleView?id=000004383&language=en_US&type=1), [Segment](https://segment.com/docs/personas/identity-resolution), Google Analytics, [AWS CloudWatch](https://hackernoon.com/capture-and-forward-correlation-ids-through-different-lambda-event-sources-220c227c65f5), etc._) will be _equally familiar_ with globally unique string-based IDs. Humans don't tend to _hand-write_ these IDs. 

The "_overhead_" to calculate the **`cid`** for a row is _negligible_ in terms of compute resource and it means that every API request sent from any client to our App has built-in message authentication (_verification_). Yes, using a 256 bit ([***32 byte***](https://www.google.com/search?q=256+bits+to+bytes)) `String`  is  4x bigger than an [**8 byte**](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL) **`Bigint`**. 
But the ***benefit*** you aren't _yet_ considering completely justifies the extra "cost". 

The way we _must_ think about Auth is that we're building an "***API-first***" application where _every_ "endpoint" (_or controller_) must accept data from a 3rd party application/client. We will be authenticating/verifying _every_ request and we need a _complete_ audit trail for every row.

Further reading: 
+ https://dba.stackexchange.com/questions/151253/non-integer-primary-key-considerations


I hope this answers your question. If not, please seek further clarification. 
Thanks! ✨

**Comment by nelsonic** [comment]
Keeping this issue **open** until it can be captured/summarised in a **`FAQ.md`**.

**Comment by nelsonic** [comment]
An area that is not covered in my original answer is: Financial Data Forensics. 
My answer is given in the context of the application we are _currently_ implementing Auth for: CS. 
When I should really be helping the OP to understand the _general_ applicability of Auth to _all_ applications. We expect to use Auth for _several_ applications including the physical access security [@home](https://github.com/dwyl/home) where we will be receiving ***payments***. _Any_ system that handles payments _automatically_ becomes a "target" for malicious hackers therefore having a verifiable transaction history is _essential_. While it might not be immediately apparent why a **CID** is relevant/useful in the context of a Role in the CS project, once you add the _wider_ context that we want to build an Auth system that can be used to grant people access to a "vault" or "home" then the need for a _comprehensive_ audit trail becomes more obvious. 
Imagine that you are building an app that will protect your life savings, in that case having a cryptographically verified hash for _every_ record might be a good idea ... 😉

**Comment by nelsonic** [comment]
After much deliberation we decided to use an `int` PK for `people.id` as we don't expect to _need_ a distributed auth system in the medium term (_for the purposes of our `app`_).
