### ISSUE TITLE
How is a client secret created for new person?

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth#68]
I've been tested the login with email feature and found that the following line crash the application:
`expected a map, got: nil` on localhost
`invalid AUTH_API_KEY/client_id please check.` on heroku (once every two login attempt)

https://github.com/dwyl/auth/blob/a3dff03c6a2cbdcd9c86e8b170ba9add41565f4f/lib/auth_web/controllers/auth_controller.ex#L364-L366

So the application doesn't manage to get a valid `client_secret` for the user so either it crashed when using the `Map.get` function on a `nil` value or it returns an error `unauthorized` with:

https://github.com/dwyl/auth/blob/a3dff03c6a2cbdcd9c86e8b170ba9add41565f4f/lib/auth_web/controllers/auth_controller.ex#L364-L366

I think this is due to the `referer` not properly set up.
I continue to investigate to see why the referer url could produce this error

**Comment by SimonLab** [comment]
Removing manually the `refer` on the verification link from the email allow us to verify the email address and to access the key  management page.

**Comment by SimonLab** [comment]
I think this is the cause of the issue:
https://github.com/dwyl/auth/blob/a3dff03c6a2cbdcd9c86e8b170ba9add41565f4f/lib/auth_web/controllers/auth_controller.ex#L69-L73

When there isn't a referrer, one is automatically created with a client_id.
I'm not sure about the logic yet so I need to check the `AuthPlug.Token.client_id()` function first

**Comment by nelsonic** [comment]
@SimonLab as we clarified on our Remote Pairing (Zoom) call, 
the problem you were facing is that the `seeds.exs` file creates a API Key during `mix ecto.setup` which uses the default url for a Phoenix App: `"www.example.com"`.
When the verify action attempts to lookup the `client_secret` from the `state` (URL) it will not match because `"localhost:4000" !== "www.example.com"` 😞 

What you need to do to get this working on your `localhost` is edit _two_ files:

First: the `auth_url` in the `router.ex` needs to be updated:
https://github.com/dwyl/auth/blob/a3dff03c6a2cbdcd9c86e8b170ba9add41565f4f/lib/auth_web/router.ex#L31
from: `"https://dwylauth.herokuapp.com"`
to: `"http://localhost:4000"`

And then in the `seeds.exs` file the `"url" => "www.example.com"`
https://github.com/dwyl/auth/blob/a3dff03c6a2cbdcd9c86e8b170ba9add41565f4f/priv/repo/seeds.exs#L43
Needs to be: `"url" => "http://localhost:4000"`

Copy the resulting `AUTH_API_KEY:` value that is generated by `mix ecto.setup` into your `.env` file, run `source .env` and then re-run the app `mix phx.server` 

Now it will work as you expect. 👍 

The _reason_ I have left the `auth_url` hard-coded in the `router.ex` file for MVP is just for simplicity. We can absolutely make it an Environment Variable in a next iteration. 
I don't really care how many environment variables we have in the Auth app.
All I care is that our "_Main_" App https://github.com/dwyl/app only requires _one_. 
Hence the effort made in PR #43 to create a _single_ `AUTH_API_KEY`.
Which is demonstrated in: https://github.com/dwyl/auth_plug_example

Hope this helps clarify. 🤞 
Thanks again for opening this issue. It helps me be more "Shoshin" in my work. ☯️

**Comment by nelsonic** [comment]
I have updated the `seeds.exs` to not _overwrite_ the `AUTH_API_KEY` but instead _use_ the existing one in `.env`. #85 
Hope that makes life simpler.

**Comment by nelsonic** [comment]
When this App is run on `localhost` the `seeds.exs` script will create an App 
but not overwrite the `AUTH_API_KEY` (_thus `client_id` / `client_secret`_) in the `.env` file.
Also, the `AUTH_API_KEY` will be printed to `stdout` for confirmation.
So I believe this issue is fixed.

@SimonLab if you still experience any blockers related to this issue, please re-open. Thanks! 👍
