### ISSUE TITLE
Disable login page when already loggedin

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth#69]
The auth application allow a user to access the login page via the dwyl logo.
This means that you can try to login again while you have a current valid session.
This produce the following error:
`invalid AUTH_API_KEY/client_id please check.`

If the session is valid the link of the logo should redirect to the api keys management page instead of the login page

# Todo

+ [ ] Use the power of Optional Auth https://github.com/dwyl/auth_plug/issues/27 to redirect to `/profile` page if person has already logged in. 
+ [ ] Only redirect to `/profile` if there is no `auth_client_id` in the `url`

**Comment by nelsonic** [comment]
@SimonLab thanks for opening this issue.
The only reason I didn't add this feature to #43 was that the PR was _already_ too big. 👍 
From the perspective of the person _using_ our "Main" App https://github.com/dwyl/app they will simply be redirected back to the App so they won't see the Login page again. 
So I've applied **`P3`** to this so we can work on it in a future sprint (_but not necessarily "urgent"_).

**Comment by nelsonic** [comment]
I took a quick look at this today. 
Only routes "protected" by `auth_plug` have the `conn.assigns.person` so we cannot check for `conn.assigns.person` in the `AuthWeb.AuthController.index/2` unless we add the `:auth` pipeline to the route that invokes that function. 

Basically we need to add a public function to [`auth_plug.ex`](https://github.com/dwyl/auth_plug/blob/master/lib/auth_plug.ex)
to extract the session from `conn` and setup `conn.assigns.person` if the `JWT` is valid.
Then we can redirect to a "logged in" page e.g. `/profile`. 
Ideally we can do this _transparently_ in the `router.ex` so that we don't have if statements everywhere. 

It should take _less_ than **`T4h`**, but we need to make it _reuse-able_ (_tested+documented_)
so that anyone else using

**Comment by nelsonic** [comment]
When _first_ visiting the Auth App home page: http://localhost:4000 
we see the login buttons + email address field: (_nothing new there_)
![image](https://user-images.githubusercontent.com/194400/94623500-40386400-02ac-11eb-877d-b78afc04804a.png)

Now with Optional Auth enabled https://github.com/dwyl/auth_plug#optional-auth
If the person is already logged in, they will see the `/profile` page:
![image](https://user-images.githubusercontent.com/194400/94623395-fb143200-02ab-11eb-912e-00ad6a53cfa4.png)

i.e. the Login Buttons are no longer visible if the person is logged in. ✅

**Comment by nelsonic** [comment]
Included in #123 📦
